### ISSUE TITLE
(Info, Feature request and question) R36S works even without support 

### ISSUE THREAD

**Issue by MrPurple666** [steward-fu/nds#65]
Related to Issue #61 I tested the myoo mini plus binary on my r36S (with arkOS) and it works perfectly well (although the shortcuts don't work), so, three questions:

• Will there be official support for it at some point? 
•How can I activate the refined menu?
•Is there any way to set the shortcut button?

Photo of binary working:
![PXL_20240322_130116525.jpg](https://github.com/steward-fu/nds/assets/78635632/8dc69bc1-8c29-47fd-9d6f-c25d74307dce)

**Comment by steward-fu** [comment]
Q: Will there be official support for it at some point ?
A: I am not sure about this because I need spend time to find any available developmen tool for R36S.

Q: How can I activate the refined menu?
A: It turns on by default. If you can not enter the refined menu, it means the SDL2 library you are using is from the stock system, not miyoo mini.

Q: Is there any way to set the shortcut button?
A: It is in config/drastic.cfg file.

**Comment by steward-fu** [comment]
For R36S support, please use this ticket: https://github.com/steward-fu/nds/issues/61
Thanks
